### ISSUE TITLE
Wildcards in url?

### ISSUE THREAD

**Issue by prewk** [nutboltu/storybook-addon-mock#54]
Thanks for a great addon!

I'm trying to dig up whether I can use some wildcard features in the url (or "match strategies")... any pointers or straight *no*?

My problem is that I have a `/api/foos` url that's paginated like this `/api/foos?skip=0&limit=20&dir=desc&sort=blabla` which is a bit flaky and tedious in my simple Storybook test where I just wanna control what's returned, no matter the querystring. So being able to do `url: "/api/foos" somehow and still match it would be nice.

Thanks!

**Comment by nutboltu** [comment]
This package supports
> Supports both named parameters (/:foo/:bar) and query parameters(/foo?bar=true)

You can easily achieve this by passing query parameters with any value. This package won't check the value of the params but check the keys to match.

```/api/foos?skip=anything&limit=anything&dir=anything&sort=anything```

The above should work for you. then you can modify the response with your desired value.

**Comment by prewk** [comment]
Ahh I misinterpreted the instructions, thanks a lot!

**Comment by nad182** [comment]
I've got a question related to this: how to use wildcards in more complex (dynamic) URLs? I'm trying to intersect/mock a URL sent to Google Maps API, which looks like this:
https://maps.googleapis.com/maps/api/place/js/AutocompletionService.GetPredictionsJson?1sQUERIED_STRING&4sen-CA&15e3&21m1&2e1&callback=_xdc_._amopoh&key=API_KEY&token=12345
As you can see, these are not simple query params, like `?bar=foo`. Instead, the param **key** is dynamic: in the example above the first param's key is `1sQUERIED_STRING_1` and if I were to query "xyz". it would be `1sxyz`. It also doesn't have the `=` sign. The same case is with the second param.

PS. I might be misinterpreting the params, and the first key is everything until the first `=` sign, which would mean that the first param (key/value) is `1sQUERIED_STRING&4sen-CA&15e3&21m1&2e1&callback=_xdc_._amopoh`, but that still makes the key dynamic, since `QUERIED_STRING` will be different based on user input.
